name: Update HTB & Tryhackme badges

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-profile-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install beautifulsoup4

      - name: Run Update Scripts
        env:
          HTB_TOKEN: ${{ secrets.HTB_TOKEN }}
        run: |
          python update_htb.py
          python update_thm.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: update security stats cards"
          file_pattern: "assets/htb-stats.svg assets/thm-stats.svg assets/htb_state.json"
